query getPosts {
  posts(where: {tag: "tab"}) {
    edges {
      node {
        id
        content
        title
        tags {
          edges {
            node {
              id
              name
              posts {
                nodes {
                  content
                }
              }
            }
          }
        }
      }
    }
  }
}